language: node_js
node_js:
- '6'
script: npm test
deploy:
  provider: heroku
  api_key:
    secure: EsgaIjknRsiChgezU+x17+IPfoKUIctnvjXfpB3bttUTFvnd8bai/6MgeqCczok+wN9E9ROC3CWBGZDy0gHjYDX0YbZTXnSBYjREicZktB7ZjBAuiOrAqxapzH/bvL3zcN72KaLUFUq2lETJMDGALAv0N9TE0clMe8XKYA07jsgZ/GVhjZ+v0m4gSjAi7e4iFDZO8oVdsxsy3A82EoBnGPusLIg5TrqTadtV1dfnHTTgfKpCdbHEpWOBkjBj9Al4djXE0h3aHDE19/7xHMDCg/+uPL6lzzlRTb90HcfnvNB82YTjbCixklfkMytrVxzUE5LHsjbbZgWN1rLuvXtsEGtd14musQokxdkRTLvtyQLMUeN45GFsLBe97ujWDApsC2PhsqsRuoFq7kFczJL0/nObtvIcXtcjGUDdIcfeRBijPZU46k8h5NqNCiv2iZOO05fRdfdcJvdxpOLdUxeGw5+5MOWF1Nl3FmlVuGoSagQW3wpejbVTPa3RwZv7SB/NQjbVfmFaXZfcCfDLuHYXIfln9ONSUPJdZQtjhXVaTXR1o2I//z5UNvx1UUV+ES6fAjeT9RYt2r8w7O3RNreLmNk16J6otCQhqY8MvNWcomODbfwAXl3pcOTgpCALFj94SN+oL+YKs+FZBLNn0+iiEq1A3o+zAOahwa6IAC1X6OE=
  app: yoyosan-stopcozi-web
  on:
    repo: yoyosan/StopCozi-web
